# Generated by Django 5.0.2 on 2024-06-06 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_rack_rackitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdevice",
            name="connection_type",
            field=models.CharField(
                choices=[("ETHERNET", "Ethernet"), ("WIFI", "Wifi")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="clientdevice",
            name="vlan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="network.vlan",
            ),
        ),
        migrations.CreateModel(
            name="NetworkDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mac_address", models.CharField(max_length=17, unique=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, unique=True),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[("ETHERNET", "Ethernet"), ("WIFI", "Wifi")],
                        max_length=10,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ROUTER", "Router"),
                            ("SWITCH", "Switch"),
                            ("ACCESS_POINT", "Access_point"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vlan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="network.vlan",
                    ),
                ),
                (
                    "wifi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="network.wifinetwork",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
