# Generated by Django 5.0.2 on 2024-06-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electric", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuit",
            name="breaker_type",
            field=models.CharField(
                choices=[
                    ("fuse", "Fuse"),
                    ("mcb", "MCB"),
                    ("rcd", "RCD"),
                    ("RCBO", "rcbo"),
                    ("gfci", "GFCI"),
                ],
                max_length=10,
            ),
        ),
    ]
